### ISSUE TITLE
image url is invalid will lead to crash,so how to  solve it

### ISSUE THREAD

**Issue by xinqidian** [cuzv/PhotoBrowser#1]

**Comment by cuzv** [comment]
Actual, It will not crash even if you set the wrong urls, In my demo case.
You should insure the url is valid before you use it.
Could you please post more information about the crash?

**Comment by xinqidian** [comment]
Sorry,it's my fault,  how to do some cache if I want

**Comment by cuzv** [comment]
Maybe you could load image use some framework can cache images, like [SDWebImage](https://github.com/rs/SDWebImage), [YYWebImage](https://github.com/ibireme/YYWebImage)

**Comment by xinqidian** [comment]
Thank you!!!

**Comment by xinqidian** [comment]
我刚才把图片那使用了 SDWebImage    datasource中  的viewController:(PBViewController *)viewController presentImageView:(UIImageView *)imageView forPageAtIndex:(NSInteger)index  方法改成  NSString *path = _highDefinitionImages[index];
        [imageView sd_setImageWithURL:[NSURL URLWithString:path] placeholderImage:[UIImage imageNamed:@"logo"]];  
可能是出现了一个bug, 有的  有的时候会不能左右滑动  但是可以点击取消退出

**Comment by cuzv** [comment]
如果只有一张图片的时候就不能左右滑动的。
可不可再描述清楚一点儿你的问题，没听太懂....
