### ISSUE TITLE
发现内存泄漏诶

### ISSUE THREAD

**Issue by xtuphe** [cuzv/PhotoBrowser#10]

**Comment by cuzv** [comment]
能否说下你遇到的问题的重现流程？

**Comment by xtuphe** [comment]
应该是在PBViewController 650行那里循环引用了，我看你在最上面也写了dealloc，并没有走dealloc不是？不过在leak上查好像并查不到 - -

**Comment by cuzv** [comment]
嗯，应该传 strong_self，多谢提醒。
