### ISSUE TITLE
你好, 预览图片时为什么我的图片不能通过手势方法和缩小

### ISSUE THREAD

**Issue by lixiaonan** [cuzv/PhotoBrowser#14]
预览图片时为什么我的图片不能通过手势方法和缩小,  Demo中可以, 可我设置的我Demo中的一样, 为什么没有放大和缩小的效果, 请问通过哪里设置呢? 谢谢

**Comment by cuzv** [comment]
当图片自身尺寸过小的时候，最大缩放scale是1.0f,所以...
https://github.com/cuzv/PhotoBrowser/blob/master/Sources/PBImageScrollView.m#L190

**Comment by lixiaonan** [comment]
好的, 谢谢, 已解决

**Comment by cuzv** [comment]
不用谢，:}
