### ISSUE TITLE
PBViewController.m文件第342行是不是写错了

### ISSUE THREAD

**Issue by Bruce-pac** [cuzv/PhotoBrowser#17]
<img width="883" alt="2017-11-26 8 54 13" src="https://user-images.githubusercontent.com/15521919/33240143-443d0634-d2ec-11e7-8a8f-595f4b549239.png">

**Comment by cuzv** [comment]
咦，这怎么编译过了的。==

**Comment by qinqi777** [comment]
可能是因为在else里面~
