### ISSUE TITLE
长图无法缩放？

### ISSUE THREAD

**Issue by laoJun666** [cuzv/PhotoBrowser#18]
为什么长图无法缩放呢 ？
![image](https://user-images.githubusercontent.com/13267315/34513034-0cb34ab6-f0a1-11e7-8b46-fdd499adb080.png)

**Comment by laoJun666** [comment]
手指在上上面捏合，图片无法跟随缩放

**Comment by cuzv** [comment]
没有发现你说的这个问题呢，你用的系统的默认图片，这个不是长图吧。
