### ISSUE TITLE
能否添加保存到本地的按钮或者事件

### ISSUE THREAD

**Issue by jianjianhao** [cuzv/PhotoBrowser#21]

**Comment by cuzv** [comment]
实现 `PBViewControllerDelegate `，提供了单击和长按手势回调。

**Comment by Asingers** [comment]
长按手势时间能否给个接口设置一下，目前的太久了，在线等😄

**Comment by Asingers** [comment]
> 实现 `PBViewControllerDelegate `，提供了单击和长按手势回调。

长按手势时间能否给个接口设置一下，目前的太久了，在线等😄
