### ISSUE TITLE
放大缩小问题

### ISSUE THREAD

**Issue by zgg141182** [cuzv/PhotoBrowser#22]
大佬，更新了最新版本，为什么放大缩小手势不管用了？

**Comment by zgg141182** [comment]
有的能，有的不能，可能是图片原因

**Comment by cuzv** [comment]
图片过小不能放大，https://github.com/cuzv/PhotoBrowser/blob/master/Sources/PBImageScrollView.m#L196

**Comment by mistdon** [comment]
@cuzv 这个缩放比例能否放开自定义？有时候产品需要这样的需求(小图也可以缩放)😊

**Comment by cuzv** [comment]
@momo13014 想改的话直接 swizzle `_setMaximumZoomScale `, 按照你喜欢的参数设置即可。或者直接提个 PR，我来合并吧，犯懒。
