### ISSUE TITLE
PBImageScrollerViewController.m     92行

### ISSUE THREAD

**Issue by maltsugar** [cuzv/PhotoBrowser#23]
进度回调需要在主线程

**Comment by cuzv** [comment]
最好在调用回调的地方保证回到主线程，而不是回调里面去回到主线程调用

**Comment by cuzv** [comment]
最好在调用回调的地方保证回到主线程，而不是回调里面去回到主线程调用

**Comment by maltsugar** [comment]
好吧，我看了系统log报警告，分析指向那里

**Comment by maltsugar** [comment]
感觉这个库挺好用的，不依赖其他库。之前看了一个依赖SDWeb版本和云信的冲突了，一直没换。今天找到这个谢谢作者。

现在有一个小问题，浏览长图，打开和缩小的动画有点突兀，希望能改下更完美

**Comment by maltsugar** [comment]
![http://wx4.sinaimg.cn/mw690/72aba7efgy1fs1ay24mksg20a90h9x6r.gif]()

**Comment by maltsugar** [comment]
![](http://wx4.sinaimg.cn/mw690/72aba7efgy1fs1ay24mksg20a90h9x6r.gif)

**Comment by cuzv** [comment]
Demo 里面有长图片的展示示例，你对比下，看看是不是使用有问题？

**Comment by maltsugar** [comment]
就是按照demo做的
这个估计是 table 嵌套 collectionView的问题
