### ISSUE TITLE
在6和6 plus上会出现滑不动的情况

### ISSUE THREAD

**Issue by zhanjiarong** [cuzv/PhotoBrowser#3]
在6和6 plus上会出现滑不动的情况，如果一直往右边滑，在某一页往右滑一点再回到这页，松开手，再想滑就滑不动了。

**Comment by cuzv** [comment]
看了一下，重现不了啊，你的每次都能重现还是偶尔的? 能不能提供详细的描述或者一个 demo?

**Comment by zhanjiarong** [comment]
你好，我录了一个小录像，就是视频后面出现的滑动时一闪一闪的，没法切换页了。我现在连是什么原因引起的都不知道，这个BUG在6和6 plus上有，6s的模拟器上也有，我的6s plus上不会出现。你看看这个BUG你有没有什么思路？6和6 plus微信朋友圈上偶尔也会出现这个问题，但是概率特别小，我项目里出现的概率特别大。

[BUG录像.zip](https://github.com/cuzv/PhotoBrowser/files/256467/BUG.zip)

**Comment by zhanjiarong** [comment]
你好，我发现了什么情况下会出现这个BUG，当图片的宽大于高的时候就会出现我上面描述的问题，而在图片高大于宽的时候正常。

**Comment by cuzv** [comment]
嗯，昨天晚上看了下，确实有bug。最近项目比较忙，可能要过几天才有时间来修复这个问题。谢谢你的反馈。

**Comment by cuzv** [comment]
@zhanjiarong 修改了，你帮忙看看还会不会出现这种问题，代码在 dev 分支上。

**Comment by cuzv** [comment]
貌似已经修复，请尝试最新发布版本 v0.3.1。
