### ISSUE TITLE
使用问题，如何在图片加载成功后依旧可以 手势放大

### ISSUE THREAD

**Issue by liujianying** [cuzv/PhotoBrowser#5]
。。

**Comment by cuzv** [comment]
当图片宽度小于屏幕宽度并且图片高度小于屏幕高度的情况下，认为图片不够清晰，所以**[禁用了放大功能](https://github.com/cuzv/PhotoBrowser/blob/master/Sources/PBImageScrollView.m#L190)**。你可以尝试增加图片 size。
