### ISSUE TITLE
为什么我修改转场动画时间没有作用

### ISSUE THREAD

**Issue by JohnnyCham** [cuzv/PhotoBrowser#6]

**Comment by cuzv** [comment]
没懂你指的具体是什么意思，能否给个稍微详细点儿的描述，或者说你修改的哪行代码。

**Comment by JohnnyCham** [comment]
[UIView animateWithDuration:0.25 delay:0 options:[self _animationOptions] animations:animations completion:completion];
[self _animationOptions]这个option是不是固定时间的，改动画时间没有用

**Comment by cuzv** [comment]
嗯，修改时间无效。这里是强制使用默认时长，aka 0.25s.

**Comment by JohnnyCham** [comment]
你的博客蛮优秀的

**Comment by JohnnyCham** [comment]
我换成普通的了 btw 你的博客蛮优秀的

**Comment by cuzv** [comment]
嗯。谢谢夸奖。
