### ISSUE TITLE
非常不错的图片浏览器

### ISSUE THREAD

**Issue by xushengxiang** [cuzv/PhotoBrowser#8]
在使用的过程中，有一个问题就是当每一个cell一张图片，多个cell复用时。会出现返回位置错误的问题，看了一下天猫淘宝在浏览买家评论图片时应该也是有这个情况，所以没有使用这种哪里弹出哪里返回的效果。不知道有没有好的解决方案

**Comment by cuzv** [comment]
你可以尝试在提供给库使用的返回图片的地方复制一份原来的 `cell` 中的 `imageView`，
即 `PBViewControllerDataSource` 中的这个方法 `thumbViewForPageAtIndex:` 看看行不行（未验证，只是一种想法）

**Comment by zhangmaliang** [comment]
很好。
